logo: "/images/jaka_cibej_fri_small.png?raw=true"
title: Jaka Čibej
description: >
 Researcher in computational/corpus linguistics and natural language processing.
 <br><br>
 Contact:
 <br>
  <a href="mailto:jaka.cibej@ff.uni-lj.si">jaka.cibej@ff.uni-lj.si</a>
  <br><br>
  Pronunciation:
   <br>
  IPA: <a href="https://ipa-reader.com/?text=%CB%88ja%CB%90ka%20%CA%A7i%CB%88b%C9%9B%CB%90%C9%AA&voice=Jan" target="_blank">/ˈjaːka ʧiˈbɛːɪ/</a>
  <br>
  X-SAMPA: /”ja:ka tSi”bE:I/
  <br>
  English Phonetic Spelling: /YA-ka chi-BAY/
   
   
theme: jekyll-theme-minimal
